# Custom flutter analyze rules used to avoid certain analyzer rules
#
# Avoid adding rules if they are not strictly needed to be avoided.

include: package:lint/analysis_options.yaml

linter:
  rules:
    avoid_classes_with_only_static_members: false
    argument_type_not_assignable: false #Consider if it should be included or not

analyzer:
  exclude:
    - lib/persistence/http/*.g.dart
  errors:
    # unused element are normally has an INFO severity but due to a bug in flutter analyzer,
    # INFO rules make flutter analyzer fail. For this time we ignore unused_element rules
    unused_element: ignore
    invalid_assignment: warning
    missing_return: error
    dead_code: info
    argument_type_not_assignable: warning