# Custom flutter analyze rules used to avoid certain analyzer rules
#
# Avoid adding rules if they are not strictly needed to be avoided.

include: package:lint/analysis_options.yaml

linter:
  rules:
    avoid_classes_with_only_static_members: false
    prefer_single_quotes: true
    avoid_relative_lib_imports: true
    sort_pub_dependencies: false

analyzer:
  exclude:
    - lib/generated/**
    - test/**.mocks.dart
  errors:
    invalid_assignment: warning
    missing_return: error
    dead_code: info
    argument_type_not_assignable: warning
    todo: info
    fixme: warning
  plugins:
    - dart_code_metrics
  language:
    strict-casts: true

dart_code_metrics:
  extends:
    - package:dart_code_metrics_presets/all.yaml
  metrics:
    cyclomatic-complexity: 15
    number-of-parameters: 6
    maximum-nesting-level: 4
  rules:
    - list-all-equatable-fields: true
    - avoid-ignoring-return-values:
        exclude:
          - test/**
    - no-empty-block:
        exclude:
          - test/**
    - arguments-ordering: false
    - format-comment: false
    - member-ordering: false
    - no-magic-number: false
    - avoid-non-null-assertion: false
    - prefer-extracting-callbacks: false
    - prefer-static-class: false
    - prefer-correct-identifier-length: false
    - binary-expression-operand-order: false
    - double-literal-format: false
    - newline-before-return: false 
    - avoid-returning-widgets: false
    - avoid-late-keyword: false
    - prefer-single-widget-per-file: false
    - avoid-passing-async-when-sync-expected: false
    - avoid-redundant-async: false
    - avoid-non-ascii-symbols: false
    - prefer-match-file-name: false
    - avoid-shrink-wrap-in-lists: false
    - no-equal-arguments: false
