coverage:
  status:
    project:
      default: false # disable the default status that measures entire project
      models: # models package
        paths:
          - lib/models/
      persistence: # persistence package
        target: 75%
        paths:
          - lib/persistence/
      pages: # pages package
        target: 75%
        paths:
          - lib/widgets/pages/
      other: # remaining
        paths:
          - "!lib/models/"
          - "!lib/persistence/"
          - "!lib/widgets/pages/"
