coverage:
  ignore:
    - "lib/base"
    - "lib/widgets"
    - "lib/features/*/presentation/widgets"
    - "lib/service_locator.dart"
    - "lib/generated"
  status:
    project:
      default: false # disable the default status that measures entire project
      lib:
        target: 70%
        paths:
          - lib/