coverage:
  status:
    project:
      default: false # disable the default status that measures entire project
      blocs: # blocs dir
        # target: 70% Not enforced at this time
        paths:
          - lib/blocs/
      data: # data dir
        target: 70%
        paths:
          - lib/data/
      payment: # payment dir
        target: 70%
        paths:
          - lib/payment/
      other: # remaining
        paths:
          - "!lib/data/"
          - "!lib/blocs/"
          - "!lib/payment/"
