coverage:
  ignore:
    - "lib/base"
    - "lib/widgets"
    - "lib/features/*/presentation/widgets"
  status:
    project:
      default: false # disable the default status that measures entire project
      lib:
        target: 80%
        paths:
          - lib/