name: Build Android app
description: Build and upload Android app
inputs:
  version:
    required: true
    description: "App version"
  build_version:
    required: true
    description: "Build version"
  store_artifacts:
    required: false
    description: "Store artifact"
  signingKeyBase64:
    required: true
    description: "Android signing key b64"
  alias:
    required: true
    description: "Android key alias"
  keyStorePassword:
    required: true
    description: "Android keystore password"
  keyPassword:
    required: true
    description: "Android key password"
  build_type:
    required: true
    description: >
      Whether to build a development or production version of the app.
      A 'development' build connects to the development backend for testing,
      while a 'production' build connects to the production backend.
      It is an error to specify a build type other than
      'development' or 'production'.

runs:
  using: "composite"
  steps:
    - name: Validate build_type
      uses: ./.github/actions/verify_build_type
      with:
        build_type: ${{ inputs.build_type }}

    - name: Setup Java
      uses: actions/setup-java@v3.13.0
      with:
        distribution: "adopt"
        java-version: 17

    - name: Setup Flutter environment
      uses: ./.github/actions/setup_flutter_environment
      with:
        build_type: ${{ inputs.build_type }}

    - name: "[dev] Build Android app (apk)"
      if: ${{ inputs.build_type == 'development' }}
      run: |
        flutter build apk --flavor development --release --build-name ${{ inputs.version }} --build-number ${{ inputs.build_version }} --target lib/main_development.dart
        mv build/app/outputs/flutter-apk/app-development-release.apk android.apk
      shell: bash

    - name: "[prod] Build Android app (app bundle)"
      if: ${{ inputs.build_type == 'production' }}
      run: |
        flutter build appbundle --flavor production --release --build-name ${{ inputs.version }} --build-number ${{ inputs.build_version }} --target lib/main_production.dart
        mv build/app/outputs/bundle/productionRelease/app-production-release.aab android.aab
      shell: bash

    - name: Sign artifact
      if: ${{ !!inputs.store_artifacts }}
      uses: r0adkll/sign-android-release@v1.0.4
      id: sign_app
      with:
        releaseDirectory: .
        signingKeyBase64: ${{ inputs.signingKeyBase64 }}
        alias: ${{ inputs.alias }}
        keyStorePassword: ${{ inputs.keyStorePassword }}
        keyPassword: ${{ inputs.keyPassword }}
      env:
        BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

    - name: "[prod] Upload app bundle"
      if: ${{ !!inputs.store_artifacts && inputs.build_type == 'production'}}
      uses: actions/upload-artifact@v3.1.3
      with:
        name: android
        path: android.aab
        retention-days: 1
        if-no-files-found: error

    - name: "[dev] Move apk file"
      if: ${{ !!inputs.store_artifacts && inputs.build_type == 'development'}}
      run: |
        mv ${{steps.sign_app.outputs.signedReleaseFile}} android.apk
      shell: bash

    - name: "[dev] Upload apk"
      if: ${{ !!inputs.store_artifacts && inputs.build_type == 'development'}}
      uses: actions/upload-artifact@v3.1.3
      with:
        name: android
        path: android.apk
        retention-days: 1
        if-no-files-found: error
