/// Flutter icons AnalogIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AnalogIcons
///      fonts:
///       - asset: fonts/AnalogIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class AnalogIcons {
  AnalogIcons._();
  static const _kFontFam = 'AnalogIcons';
  static const IconData closed = IconData(0xe800, fontFamily: _kFontFam);
}
