name: Version
description: Determine version

outputs:
  version:
    description: "Version (2.x.x)"
    value: ${{ steps.versioning.outputs.version }}
  version_tag:
    description: "Version tag (v2.x.x)"
    value: ${{ steps.versioning.outputs.version_tag }}
  build_version:
    description: "Build version (7xx)"
    value: ${{ steps.build_version.outputs.build_no }}

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Determine versioning
      uses: paulhatch/semantic-version@v4.0.3
      id: versioning
      with:
        tag_prefix: "v"
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        format: "${major}.${minor}.${patch}"
        bump_each_commit: false

    - name: Determine build version
      id: build_version
      run: |
        BUILD_NO=$((${{ github.run_number }} + 100))
        echo "::set-output name=build_no::$BUILD_NO"
      shell: bash

    - name: Print versioning
      run: |
        echo "Version: $VERSION"
        echo "Version Tag: $VERSION_TAG"
        echo "Run No: $BUILD_NO"
      env:
        VERSION: ${{ steps.versioning.outputs.version }}
        VERSION_TAG: ${{ steps.versioning.outputs.version_tag }}
        BUILD_NO: ${{ steps.build_version.outputs.build_no }}
      shell: bash