name: Setup Flutter environment
description: Setup the Flutter environment

env:
  FLUTTER_VERSION: 3.13.7

runs:
  using: "composite"
  steps:
      - name: Setup Flutter environment
        uses: subosito/flutter-action@v2.8.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"

      - name: Download dependencies
        run: flutter pub get
        shell: bash