name: Build And Deploy Coffeecard App To Firebase Distribution

on:
  workflow_run:
    workflows: ["Flutter build and test"]
    type: [complete]
    branches: [develop]

    push:
      branches: [feature/jonas/automate-ios-build]

jobs:
  build_ios:
    name: Build iOS App
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2.4.0
        with:
          distribution: "adopt"
          java-version: "11.x"
      - name: Setup Flutter environment
        uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: "2.10.2"
          channel: "stable"
      - name: Download dependencies
        run: flutter pub get
      - name: Decode google-services.json
        env:
          SERVICES_JSON: ${{ secrets.FIREBASE_IOS_SERVICES_JSON }}
        run: echo $SERVICES_JSON > ios/Runner/GoogleService-Info.plist
      - name: Generate code
        run: scripts/.generate-code.sh code
      - name: Build iOS
        run: flutter build ios --release --no-codesign
      - name: Upload iOS artefact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: ios
          path: build/ios/iphoneos
  build_apk:
    name: Build Android App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2.4.0
        with:
          distribution: "adopt"
          java-version: "11.x"
      - name: Setup Flutter environment
        uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: "2.10.2"
          channel: "stable"
      - name: Download dependencies
        run: flutter pub get
      - name: Decode google-services.json
        env:
          SERVICES_JSON: ${{ secrets.FIREBASE_ANDROID_SERVICES_JSON }}
        run: echo $SERVICES_JSON > android/app/google-services.json
      - name: Generate code
        run: scripts/.generate-code.sh code
      - name: Build APK
        run: flutter build apk
      - name: Upload Android build
        uses: actions/upload-artifact@v3.0.0
        with:
          name: android
          path: build/app/outputs/apk/release
  upload_ios:
    name: Upload iOS build to Firebase App Distribution
    runs-on: ubuntu-latest
    needs: [build_ios]

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: ios
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
        with:
          appId: ${{ secrets.FIREBASE_IOS_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: analogio-devs
          file: Runner.ipa
  upload_apk:
    name: Upload Android build to Firebase App Distribution
    runs-on: ubuntu-latest
    needs: [build_apk]

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: android
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
        with:
          appId: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: analogio-devs
          file: app-release.aap
