name: Flutter build and test

on:
  pull_request:
    branches: [develop, production]

  workflow_dispatch:

  workflow_call:

jobs:
  build-and-test:
    name: Build and test Flutter app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0
      - name: Setup Flutter environment
        uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: "3.0.0"
          channel: "stable"
      - name: Download dependencies
        run: flutter pub get
      - name: Generate code
        run: scripts/.generate-code.sh code
      - name: Check formatting
        run: flutter format --set-exit-if-changed .
      - name: Static Analysis
        run: flutter  analyze
      - name: Run tests
        run: flutter test --coverage
      - name: Upload test report to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          flags: unittests
          file: coverage/lcov.info
