name: Release Coffeecard App

on:
  pull_request:
    branches: [develop, production]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      store_artifacts: true
    secrets: inherit

  upload_ios:
    name: Upload iOS build
    runs-on: macos-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload iOS app
        uses: ./.github/actions/upload_ios
        with:
          app_store_connect_username: ${{ secrets.APP_STORE_CONNECT_USERNAME }}
          app_store_connect_password: ${{ secrets.APP_STORE_CONNECT_PASSWORD }}
          firebase_ios_app_id: ${{ secrets.FIREBASE_IOS_APP_ID }}
          firebase_token: ${{ secrets.FIREBASE_TOKEN }}

  upload_android:
    name: Upload Android build
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload Android app
        uses: ./.github/actions/upload_android
        with:
          firebase_android_app_id: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
          firebase_token: ${{ secrets.FIREBASE_TOKEN }}
          android_signing_key: ${{ secrets.ANDROID_KEYSTORE }}
          android_key_alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          android_keystore_password: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          android_Key_password: ${{ secrets.ANDROID_KEY_PASSWORD }}
          playstore_service_account: ${{ secrets.PLAYSTORE_SERVICE_ACCOUNT_JSON }}

  tag:
    name: Git Tag version
    runs-on: ubuntu-latest
    needs: [build, upload_ios, upload_android]
    if: ${{ needs.upload_ios.result == 'success' && needs.upload_android.result == 'success' && github.ref_name == 'production' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Git Tag ${{ needs.build.outputs.version_tag }}
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ needs.build.outputs.version_tag }}
