name: Publish Development App

on:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    uses: ./.github/workflows/build.yml
    with:
      storeArtifacts: true
      prodRelease: false
    secrets: inherit

  dev_upload_ios:
    name: Upload iOS build to Firebase App Distribution
    runs-on: ubuntu-latest
    needs: [build_and_test]

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: ios

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_IOS_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          # FIXME: token is deprecated, use serviceCredentialsFileContent instead
          # serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: analogio-devs
          file: Analog.ipa

  dev_upload_android:
    name: Upload Android build to Firebase App Distribution
    runs-on: ubuntu-latest
    needs: [build_and_test]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: android
          
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          # FIXME: token is deprecated, use serviceCredentialsFileContent instead
          # serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: analogio-devs
          file: app-development-release.apk
