name: Release Production App

on:
  release:
    types: [created]

jobs:
  build_and_test:
    uses: ./.github/workflows/build.yml
    with:
      storeArtifacts: true
      prodRelease: true
      tagName: ${{ github.event.release.tag_name }}
    secrets: inherit

  prod_release_ios:
    name: Upload iOS build to App Store connect
    runs-on: macos-latest
    needs: [build_and_test]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: ios
          
      - name: Upload app to App Store Connect
        env:
          APP_STORE_CONNECT_USERNAME: ${{ secrets.APP_STORE_CONNECT_USERNAME }}
          APP_STORE_CONNECT_PASSWORD: ${{ secrets.APP_STORE_CONNECT_PASSWORD }}
        run: |
          xcrun altool --upload-app -t ios -f "Analog.ipa" -u "$APP_STORE_CONNECT_USERNAME" -p "$APP_STORE_CONNECT_PASSWORD"

  prod_release_android:
    name: Upload Android build to Play Store
    runs-on: ubuntu-latest
    needs: [build_and_test]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: android

      - name: Sign Android appbundle
        uses: r0adkll/sign-android-release@v1.0.4
        id: sign_app
        with:
          releaseDirectory: .
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE }}
          alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Upload to Google Play Store
        uses: r0adkll/upload-google-play@v1.1.2
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_SERVICE_ACCOUNT_JSON }}
          packageName: dk.analog.digitalclipcard
          releaseFiles: ${{ steps.sign_app.outputs.signedReleaseFile }}
          track: internal
          status: draft
