name: Publish Development App

on:
  pull_request:
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      store_artifacts: true
      build_type: "dev"
      tag_name: ${{ github.head_ref }}
    secrets: inherit

  test:
    uses: ./.github/workflows/test.yml

  upload_ios:
    name: Upload iOS build to Firebase App Distribution
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: ios

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{ secrets.FIREBASE_IOS_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          # FIXME: token is deprecated, use serviceCredentialsFileContent instead
          # serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: analogio-devs
          file: Analog.ipa
          releaseNotes: |
            ${{ github.event.pull_request.title }}
            ${{ github.event.pull_request.html_url }}
            (branch ${{ github.head_ref }})

  upload_android:
    name: Upload Android build to Firebase App Distribution
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: android

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          # FIXME: token is deprecated, use serviceCredentialsFileContent instead
          # serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: analogio-devs
          file: android.apk
          releaseNotes: |
            ${{ github.event.pull_request.title }}
            ${{ github.event.pull_request.html_url }}
            (branch ${{ github.head_ref }})
