name: Publish Development App

on:
  push:
    branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      store_artifacts: true
      prod_release: false
    secrets: inherit

  upload_ios:
    name: Upload iOS build to Firebase App Distribution
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: ios

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.3
        with:
          appId: ${{ secrets.FIREBASE_IOS_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          # FIXME: token is deprecated, use serviceCredentialsFileContent instead
          # serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: analogio-devs
          file: Analog.ipa

  upload_android:
    name: Upload Android build to Firebase App Distribution
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: android
          
      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.3.3
        with:
          appId: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          # FIXME: token is deprecated, use serviceCredentialsFileContent instead
          # serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: analogio-devs
          file: app-development-release.apk
