name: Release Production App

on:
  release:
    types: [ created ]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      store_artifacts: true
      build_type: "prod"
      tag_name: ${{ github.event.release.tag_name }}
    secrets: inherit

  test:
    uses: ./.github/workflows/test.yml

  release_ios:
    name: Upload iOS build to App Store connect
    runs-on: macos-latest
    needs: [build, test]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: ios
          
      - name: Upload app to App Store Connect
        env:
          APP_STORE_CONNECT_USERNAME: ${{ secrets.APP_STORE_CONNECT_USERNAME }}
          APP_STORE_CONNECT_PASSWORD: ${{ secrets.APP_STORE_CONNECT_PASSWORD }}
        run: |
          xcrun altool --upload-app -t ios -f "Analog.ipa" -u "$APP_STORE_CONNECT_USERNAME" -p "$APP_STORE_CONNECT_PASSWORD"

  release_android:
    name: Upload Android build to Play Store
    runs-on: ubuntu-latest
    needs: [build, test]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: android

      - name: Upload to Google Play Store
        uses: r0adkll/upload-google-play@v1.1.2
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_SERVICE_ACCOUNT_JSON }}
          packageName: dk.analog.digitalclipcard
          releaseFiles: android
          track: internal
          status: draft
