name: Test

on:
  pull_request:
    branches: [production, develop]

jobs:
  build-and-test:
    name: Build and test Flutter app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Setup Flutter environment
        uses: ./.github/actions/setup_flutter_environment

      - name: Generate code
        run: dart run build_runner build

      - name: Check formatting
        run: dart format --set-exit-if-changed lib/

      - name: Static Analysis
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage

      - name: Upload test report to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          flags: unittests
          file: coverage/lcov.info